export const USER_ACCESS_AGENT = {
  id: "agente-usuarios-sualuma",
  name: "User Guard",
  publicName: "Agente Usuários",
  role: "Guardião de acessos, planos, usuários, permissões e lançamento da Sualuma",
  mission:
    "Manter o sistema de usuários organizado, seguro e coerente com o modelo real de negócio da Sualuma, acompanhando em tempo real cada etapa de configuração até o lançamento.",
  automaticMode: true,

  currentFocus: {
    phase: "Configuração de acessos para lançamento",
    priority:
      "Garantir que cada plano libere somente o que deve liberar e bloqueie tudo que não pertence ao acesso comprado.",
    launchGoal:
      "Deixar planos, checkouts, rotas privadas, comunidade, dashboards e Stripe coerentes para lançar hoje com segurança.",
  },

  officialAccessIds: [
    "empresa_contratante_servicos_free",
    "ia_client_basic",
    "ia_client_pro",
    "ia_client_premium",
    "provider_free",
    "service_provider",
    "admin",
  ],

  addonIds: [
    "agent_addon",
    "automation_addon",
    "skill_addon",
    "template_addon",
  ],

  accessModel: {
    empresaContratanteServicosFree: {
      code: "empresa_contratante_servicos_free",
      role: "empresa_contratante_servicos",
      publicName: "Empresa Contratante de Serviços",
      price: "R$0",
      description:
        "Acesso gratuito para empresas/pessoas que querem contratar prestadores dentro da Sualuma. Não é plano de IA e não é plano de prestador.",
      releases: [
        "Criar conta grátis.",
        "Fazer login.",
        "Acessar área básica de usuário.",
        "Acessar comunidade.",
        "Visualizar marketplace e serviços.",
        "Contratar prestadores dentro da plataforma.",
        "Enviar briefing ou pedido de serviço.",
        "Conversar com prestador dentro da plataforma.",
        "Acompanhar pedidos e entregas contratadas.",
        "Receber notificações básicas.",
        "Usar Mia com limite básico gratuito.",
        "Comprar serviços.",
        "Comprar plano IA futuramente.",
        "Comprar agentes, automações, skills ou templates avulsos se permitido.",
      ],
      blocks: [
        "Não pode anunciar serviços.",
        "Não pode vender como prestador.",
        "Não pode aparecer como prestador no catálogo.",
        "Não pode criar portfólio/vitrine profissional.",
        "Não pode acessar dashboard completo de prestador.",
        "Não pode acessar /provider-services como prestador ativo.",
        "Não pode divulgar WhatsApp.",
        "Não pode divulgar contato externo para fechar por fora.",
        "Não pode usar comunidade para vender serviço sem plano de prestador.",
        "Não pode acessar agentes pagos de IA sem plano IA ou compra avulsa.",
        "Não pode acessar automações pagas sem compra.",
        "Não pode acessar Studio.",
        "Não pode acessar Admin.",
      ],
    },

    iaClientBasic: {
      code: "ia_client_basic",
      role: "ia_client",
      level: "basic",
      publicName: "Cliente IA Basic",
      description:
        "Cliente que comprou o plano básico de IA. Recebe agentes, créditos e benefícios do nível Basic, mas não vira prestador automaticamente.",
      releases: [
        "Tudo da Empresa Contratante de Serviços.",
        "Dashboard de Cliente IA.",
        "Painel de agentes do cliente.",
        "Mia com limite do plano Basic.",
        "Agentes básicos liberados pelo plano.",
        "Histórico básico de conversas e tarefas.",
        "Compra de agentes extras.",
        "Compra de automações extras.",
        "Compra de skills extras.",
        "Compra de templates extras.",
      ],
      blocks: [
        "Não vira prestador automaticamente.",
        "Não pode anunciar serviços próprios.",
        "Não pode vender serviços sem plano de prestador.",
        "Não pode acessar dashboard completo de prestador.",
        "Não pode divulgar WhatsApp.",
        "Não pode acessar agentes Pro/Premium não comprados.",
        "Não pode acessar Studio.",
        "Não pode acessar Admin.",
      ],
    },

    iaClientPro: {
      code: "ia_client_pro",
      role: "ia_client",
      level: "pro",
      publicName: "Cliente IA Pro",
      description:
        "Cliente que comprou o plano Pro de IA. Recebe mais agentes, mais créditos e recursos avançados, mas não vira prestador automaticamente.",
      releases: [
        "Tudo do Cliente IA Basic.",
        "Mais créditos da Mia.",
        "Mais agentes de IA.",
        "Agentes intermediários/profissionais.",
        "Mais automações liberadas.",
        "Recursos avançados de produtividade, conteúdo, atendimento, funil e negócio.",
        "Add-ons extras conforme compra.",
      ],
      blocks: [
        "Não vira prestador automaticamente.",
        "Não pode vender serviços sem plano de prestador.",
        "Não pode acessar ferramentas completas de prestador.",
        "Não pode divulgar WhatsApp.",
        "Não pode acessar Premium se não estiver incluído ou comprado.",
        "Não pode acessar Studio.",
        "Não pode acessar Admin.",
      ],
    },

    iaClientPremium: {
      code: "ia_client_premium",
      role: "ia_client",
      level: "premium",
      publicName: "Cliente IA Premium",
      description:
        "Cliente com maior pacote de IA. Libera agentes premium, mais créditos, mais automações e dashboard mais completo de Cliente IA.",
      releases: [
        "Tudo do Cliente IA Pro.",
        "Maior limite de créditos da Mia.",
        "Agentes premium.",
        "Mais automações.",
        "Mais skills.",
        "Mais templates.",
        "Recursos avançados de estratégia, operação, atendimento, conteúdo e vendas.",
        "Dashboard mais completo de Cliente IA.",
      ],
      blocks: [
        "Não vira prestador automaticamente.",
        "Não pode anunciar serviços sem plano de prestador.",
        "Não pode vender por fora.",
        "Não pode divulgar WhatsApp.",
        "Não pode acessar Studio.",
        "Não pode acessar Admin.",
        "Não pode moderar comunidade.",
        "Não pode ver dados de outros usuários.",
      ],
    },

    providerFree: {
      code: "provider_free",
      role: "provider_free",
      publicName: "Prestador de Serviços Gratuito Limitado",
      description:
        "Prestador com acesso gratuito limitado. Pode testar a área de prestação de serviços, mas paga taxa administrativa por venda ou serviço prestado.",
      releases: [
        "Criar perfil básico de prestador.",
        "Acessar área limitada de prestador.",
        "Responder solicitações recebidas dentro da plataforma.",
        "Entregar serviço dentro da plataforma.",
        "Pagar taxa administrativa por venda ou serviço prestado.",
        "Ter histórico básico de entregas.",
        "Conversar com clientes dentro da plataforma.",
      ],
      blocks: [
        "Não pode anunciar livremente no marketplace.",
        "Não pode destacar serviços.",
        "Não pode criar vitrine completa.",
        "Não pode divulgar WhatsApp.",
        "Não pode levar cliente para fora da plataforma.",
        "Não pode vender por fora.",
        "Não vira Cliente IA automaticamente.",
        "Não acessa agentes pagos de IA sem plano IA ou compra avulsa.",
        "Não acessa Studio.",
        "Não acessa Admin.",
        "Não pode usar comunidade como vitrine livre.",
      ],
    },

    serviceProvider: {
      code: "service_provider",
      role: "service_provider",
      publicName: "Prestador de Serviços Profissional",
      description:
        "Prestador com plano profissional. Pode anunciar, vender, receber pedidos e entregar serviços dentro da plataforma.",
      releases: [
        "Tudo do provider_free.",
        "Dashboard completo de prestador.",
        "Acesso a /provider-services.",
        "Criar serviços.",
        "Editar serviços.",
        "Anunciar serviços dentro da plataforma.",
        "Aparecer no marketplace.",
        "Criar portfólio/vitrine.",
        "Receber propostas.",
        "Enviar propostas.",
        "Gerenciar entregas.",
        "Gerenciar reuniões.",
        "Gerenciar mensagens com clientes.",
        "Acessar oportunidades.",
        "Acessar métricas básicas de vendas/serviços.",
        "Comprar agentes, automações e skills extras se quiser.",
      ],
      blocks: [
        "Não vira Cliente IA automaticamente.",
        "Não libera agentes IA de cliente se não comprou plano IA.",
        "Não pode divulgar WhatsApp.",
        "Não pode fechar serviço por fora.",
        "Não pode burlar taxa ou comissão.",
        "Não pode acessar Studio.",
        "Não pode acessar Admin.",
        "Não pode ver dados de outros prestadores.",
        "Não pode ver dados privados de clientes fora dos próprios contratos.",
        "Não pode moderar comunidade.",
      ],
    },

    admin: {
      code: "admin",
      role: "admin",
      publicName: "Admin",
      description:
        "Acesso interno soberano. Não é plano público, não aparece no checkout e não pode ser comprado.",
      releases: [
        "Acesso total ao Studio.",
        "Acesso total ao Admin.",
        "Acesso a todos os subdomínios.",
        "Acesso a /studio.",
        "Acesso a /studio/usuarios.",
        "Acesso a /studio/usuarios-diagnostico.",
        "Acesso a /studio/mia-brain.",
        "Acesso a /studio/stripe-planos.",
        "Acesso a /admin.",
        "Acesso aos agentes administrativos.",
        "Acesso ao Copiloto.",
        "Acesso ao User Guard.",
        "Acesso a diagnósticos internos.",
        "Acesso a usuários, planos, métricas, moderação e alertas.",
      ],
      blocks: [
        "Não aparece como plano público.",
        "Não aparece no checkout.",
        "Não pode ser comprado.",
        "Não pode ser selecionado por usuário comum.",
        "Não deve ser alterado por webhook comum do Stripe.",
        "Não deve ser concedido automaticamente.",
        "Não deve ser exposto em resposta pública de API.",
      ],
    },
  },

  routesToAudit: {
    publicPlanRoutes: [
      "/plans",
      "/planos",
      "/services/plans",
      "/servicos/planos",
      "/prestador/planos",
      "/flowmind/planos",
    ],
    internalPlanRoutes: [
      "/studio/stripe-planos",
    ],
    stripeRoutes: [
      "/api/stripe/checkout",
      "/api/stripe/checkout-price",
      "/api/stripe/checkout-service-plan",
    ],
    clientRoutes: [
      "/member-user",
      "/cliente/indique",
      "/automations",
    ],
    providerRoutes: [
      "/provider-services",
      "/prestador/planos",
    ],
    internalRoutes: [
      "/studio",
      "/studio/usuarios",
      "/studio/usuarios-diagnostico",
      "/studio/mia-brain",
      "/admin",
      "/admin/leads",
      "/admin/emails",
      "/estudio-lab/agentesadms",
      "/studio-lab/copilot",
    ],
  },

  communityRules: {
    baseAccess: "Todos os usuários logados",
    releases: [
      "Todos os usuários logados podem acessar.",
      "Usuários podem postar conteúdo permitido.",
      "Usuários podem comentar.",
      "Prestador profissional pode divulgar serviço dentro das regras.",
      "Admin pode moderar.",
    ],
    blocks: [
      "Bloquear WhatsApp.",
      "Bloquear telefone.",
      "Bloquear e-mail usado para venda externa.",
      "Bloquear 'me chama no direct'.",
      "Bloquear links externos de venda.",
      "Bloquear anúncio de serviço para quem não é service_provider.",
      "Bloquear spam.",
      "Bloquear promessa enganosa.",
      "Bloquear tentativa de tirar cliente da Sualuma.",
      "Bloquear contratação por fora.",
    ],
  },

  realtimeTracking: {
    enabled: true,
    progressFile: "data/user-access-agent/progress.json",
    mustTrack: [
      "Etapa iniciada.",
      "Etapa concluída.",
      "Rota revisada.",
      "Regra aplicada.",
      "Teste pendente.",
      "Teste aprovado.",
      "Risco encontrado.",
      "Ação pendente para lançamento.",
    ],
  },

  rules: [
    "Empresa Contratante de Serviços pode contratar prestador sem comprar pacote IA.",
    "Empresa Contratante de Serviços não é prestadora.",
    "Cliente IA não vira prestador automaticamente.",
    "Prestador não vira Cliente IA automaticamente.",
    "Usuário só acessa os dois mundos se tiver os dois acessos separadamente.",
    "Admin acessa tudo.",
    "Comunidade é para todos os logados, mas sem WhatsApp, venda externa, spam ou tentativa de tirar cliente da plataforma.",
    "Toda comunicação e entrega de serviço deve acontecer dentro da Sualuma.",
    "Cada plano libera somente os agentes do próprio plano.",
    "Dashboard deve mostrar apenas recursos do plano + add-ons comprados.",
    "Agentes extras podem ser comprados na loja de agentes.",
    "Automações extras podem ser compradas na loja de automações.",
    "Skills extras podem ser compradas na loja de skills.",
    "Templates extras podem ser comprados na loja de templates.",
    "Mia é a chefe/orquestradora do sistema; o limite de créditos muda por plano.",
    "Plano Prime não existe e não deve ser usado nas regras.",
    "Stripe deve atualizar somente o acesso correspondente ao produto comprado.",
    "Supabase/banco deve guardar acessos separados, não misturados.",
  ],

  dashboards: {
    clientDashboard: {
      path: "/member-user",
      subdomain: "dashboardcliente.sualuma.online",
      allowedAccess: [
        "empresa_contratante_servicos_free",
        "ia_client_basic",
        "ia_client_pro",
        "ia_client_premium",
        "admin",
      ],
      agentPanel: "client_agent_dashboard",
    },
    providerDashboard: {
      path: "/provider-services",
      subdomain: "meuservico.sualuma.online",
      allowedAccess: [
        "provider_free",
        "service_provider",
        "admin",
      ],
      agentPanel: "provider_agent_dashboard",
    },
    community: {
      requiredAccess: "logged_user",
      moderation:
        "Bloquear divulgação de WhatsApp, telefone, contato externo, serviços externos e ofertas sem plano service_provider.",
    },
    studio: {
      requiredAccess: "admin",
      paths: [
        "/studio",
        "/studio/usuarios",
        "/studio/usuarios-diagnostico",
        "/studio/mia-brain",
        "/studio/stripe-planos",
        "/admin",
      ],
    },
  },
};
